//! Build script: embed Windows .exe icon from DualSense SVG (same as tray).

#[allow(dead_code)]
#[path = "src/ui/svg_icon.rs"]
mod svg_icon;

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const DISPLAY_NAME: &str = "SDSC Utils";
const TRAY_SIZE: u32 = 32;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let connected = svg_icon::render_dualsense_connected_rgba(TRAY_SIZE)
        .expect("rasterize connected DualSense icon");
    let dim = svg_icon::render_dualsense_dim_rgba(TRAY_SIZE).expect("rasterize dim DualSense icon");

    write_embedded_bytes(&out_dir, &connected, &dim);

    let changelog_src = fs::read_to_string("assets/CHANGELOG.md").unwrap_or_default();
    let releases = parse_changelog(&changelog_src);
    write_changelog(&out_dir, &releases);

    #[cfg(windows)]
    {
        write_app_ico(&out_dir);
        let ico_path = out_dir.join("app.ico");
        let mut res = winres::WindowsResource::new();
        res.set_icon(ico_path.to_str().expect("utf-8 icon path"));
        res.set("ProductName", DISPLAY_NAME);
        res.set(
            "FileDescription",
            "Show DualSense controller battery levels in the system tray",
        );
        if let Err(err) = res.compile() {
            // Missing Windows SDK / RC tooling should not block non-icon builds in CI-like envs.
            println!("cargo:warning=winres failed to embed icon: {err}");
        }
    }

    println!("cargo:rerun-if-changed=assets/CHANGELOG.md");
    println!("cargo:rerun-if-changed=src/ui/svg_icon.rs");
    println!("cargo:rerun-if-changed=assets/icons/dualsense.svg");
    println!("cargo:rerun-if-changed=assets/icons/settings.svg");
    println!("cargo:rerun-if-changed=assets/icons/identify.svg");
    println!("cargo:rerun-if-changed=assets/icons/power.svg");
    println!("cargo:rerun-if-changed=assets/icons/close.svg");
    println!("cargo:rerun-if-changed=assets/icons/minimize.svg");
    println!("cargo:rerun-if-changed=assets/icons/check.svg");
    println!("cargo:rerun-if-changed=build.rs");
}

fn write_embedded_bytes(out_dir: &Path, connected: &[u8], dim: &[u8]) {
    let path = out_dir.join("icon_embedded.rs");
    let mut file = fs::File::create(&path).expect("create icon_embedded.rs");
    writeln!(file, "pub const CONNECTED_RGBA: &[u8] = &{:?};", connected).unwrap();
    writeln!(file, "pub const DIM_RGBA: &[u8] = &{:?};", dim).unwrap();
}

type ChangelogItems = Vec<String>;
type ChangelogSections = Vec<(String, ChangelogItems)>;
type ChangelogReleases = Vec<(String, ChangelogSections)>;

fn parse_changelog(src: &str) -> ChangelogReleases {
    let mut releases: ChangelogReleases = Vec::new();
    let mut current_version: Option<String> = None;
    let mut current_sections: Vec<(String, Vec<String>)> = Vec::new();
    let mut current_section: Option<(String, Vec<String>)> = None;

    let flush_section =
        |current_section: &mut Option<(String, Vec<String>)>,
         current_sections: &mut Vec<(String, Vec<String>)>| {
            if let Some((title, items)) = current_section.take() {
                current_sections.push((title, items));
            }
        };

    for raw in src.lines() {
        let line = raw.trim();
        if let Some(rest) = line.strip_prefix("### ") {
            if current_version.is_none() {
                continue;
            }
            flush_section(&mut current_section, &mut current_sections);
            current_section = Some((rest.trim().to_string(), Vec::new()));
        } else if let Some(rest) = line.strip_prefix("## ") {
            flush_section(&mut current_section, &mut current_sections);
            if let Some(version) = current_version.take() {
                releases.push((version, std::mem::take(&mut current_sections)));
            }
            current_version = Some(rest.trim().to_string());
        } else if let Some(rest) = line.strip_prefix("- ").or_else(|| line.strip_prefix("* "))
            && let Some((_, items)) = current_section.as_mut()
        {
            items.push(rest.trim().to_string());
        }
        // Everything else is ignored.
    }

    flush_section(&mut current_section, &mut current_sections);
    if let Some(version) = current_version.take() {
        releases.push((version, current_sections));
    }
    releases
}

fn escape_changelog_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn write_changelog(out_dir: &Path, releases: &[(String, ChangelogSections)]) {
    let path = out_dir.join("changelog_generated.rs");
    let mut file = fs::File::create(&path).expect("create changelog_generated.rs");
    writeln!(
        file,
        "// Auto-generated by build.rs from assets/CHANGELOG.md — do not edit."
    )
    .unwrap();
    writeln!(
        file,
        "pub struct ChangelogSection {{ pub title: &'static str, pub items: &'static [&'static str] }}"
    )
    .unwrap();
    writeln!(
        file,
        "pub struct ChangelogRelease {{ pub version: &'static str, pub sections: &'static [ChangelogSection] }}"
    )
    .unwrap();
    writeln!(file, "pub static CHANGELOG: &[ChangelogRelease] = &[").unwrap();
    for (version, sections) in releases {
        writeln!(file, "    ChangelogRelease {{").unwrap();
        writeln!(
            file,
            "        version: \"{}\",",
            escape_changelog_str(version)
        )
        .unwrap();
        writeln!(file, "        sections: &[").unwrap();
        for (title, items) in sections {
            writeln!(file, "            ChangelogSection {{").unwrap();
            writeln!(
                file,
                "                title: \"{}\",",
                escape_changelog_str(title)
            )
            .unwrap();
            writeln!(file, "                items: &[").unwrap();
            for item in items {
                writeln!(
                    file,
                    "                    \"{}\",",
                    escape_changelog_str(item)
                )
                .unwrap();
            }
            writeln!(file, "                ],").unwrap();
            writeln!(file, "            }},").unwrap();
        }
        writeln!(file, "        ],").unwrap();
        writeln!(file, "    }},").unwrap();
    }
    writeln!(file, "];").unwrap();
}

#[cfg(windows)]
fn write_app_ico(out_dir: &Path) {
    use ico::{IconDir, IconDirEntry, IconImage, ResourceType};

    let mut icon_dir = IconDir::new(ResourceType::Icon);
    for size in [16u32, 32, 48, 256] {
        let rgba = svg_icon::render_dualsense_connected_rgba(size)
            .unwrap_or_else(|err| panic!("rasterize DualSense {size}x{size}: {err}"));
        let image = IconImage::from_rgba_data(size, size, rgba);
        icon_dir.add_entry(IconDirEntry::encode(&image).expect("encode ico entry"));
    }

    let ico_path = out_dir.join("app.ico");
    let file = fs::File::create(&ico_path).expect("create app.ico");
    icon_dir.write(file).expect("write app.ico");
}

#[cfg(test)]
mod tests {
    use super::{escape_changelog_str, parse_changelog, write_changelog};

    #[test]
    fn parses_multiple_releases() {
        let src = "## 1.7.0\n### Added\n- Foo\n### Fixed\n- Bar\n## 1.6.0\n### Added\n* Baz\n";
        let releases = parse_changelog(src);
        assert_eq!(releases.len(), 2);
        assert_eq!(releases[0].0, "1.7.0");
        assert_eq!(releases[0].1.len(), 2);
        assert_eq!(releases[0].1[0].0, "Added");
        assert_eq!(releases[0].1[0].1, vec!["Foo".to_string()]);
        assert_eq!(releases[0].1[1].0, "Fixed");
        assert_eq!(releases[0].1[1].1, vec!["Bar".to_string()]);
        assert_eq!(releases[1].0, "1.6.0");
        assert_eq!(releases[1].1.len(), 1);
        assert_eq!(releases[1].1[0].1, vec!["Baz".to_string()]);
    }

    #[test]
    fn parses_single_section_release() {
        let src = "## 1.5.0\n### Fixed\n- Only fix\n";
        let releases = parse_changelog(src);
        assert_eq!(releases.len(), 1);
        assert_eq!(releases[0].0, "1.5.0");
        assert_eq!(releases[0].1.len(), 1);
        assert_eq!(releases[0].1[0].0, "Fixed");
        assert_eq!(releases[0].1[0].1, vec!["Only fix".to_string()]);
    }

    #[test]
    fn empty_input_returns_empty_vec() {
        assert!(parse_changelog("").is_empty());
        assert!(parse_changelog("Some prose\n- stray bullet\n").is_empty());
    }

    #[test]
    fn escaping_round_trip_for_quotes_and_backslashes() {
        let item = "say \"hi\" with \\ backslash".to_string();
        let releases = vec![(
            "1.7.0".to_string(),
            vec![("Added".to_string(), vec![item.clone()])],
        )];
        let dir = std::env::temp_dir().join(format!(
            "sdsc_changelog_test_{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        write_changelog(&dir, &releases);
        let generated = std::fs::read_to_string(dir.join("changelog_generated.rs")).unwrap();
        assert!(generated.contains(&format!("\"{}\"", escape_changelog_str(&item))));
        assert!(generated.contains("\\\""));
        assert!(generated.contains("\\\\"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
